version: "3.7"
services:

  server:
    build: .
    container_name: "et-server"
    ports:
      - 8000
    depends_on:
      - mongodb

  mongodb:
    image: "mongo:4.1.13-bionic"
    container_name: "mongodb"
    ports:
      - 27017
    volumes:
      - ${DB_DATA_DIR}:/data/db
      - ${DB_LOG_DIR}:/logs/db
